# Generated by Django 3.1.7 on 2021-03-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0002_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='date',
            field=models.DateTimeField(verbose_name='%Y-%m-%d %H:%M:%S'),
        ),
    ]
