# Generated by Django 3.1.7 on 2021-03-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0003_auto_20210306_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
