# Generated by Django 3.1.7 on 2021-03-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0005_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='tutors',
        ),
        migrations.AddField(
            model_name='journeyuser',
            name='subjects',
            field=models.ManyToManyField(related_name='journeyusers', related_query_name='journeyuser', to='capstoneapi.Subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='label',
            field=models.CharField(max_length=150),
        ),
    ]
