# Generated by Django 3.1.7 on 2021-03-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capstoneapi', '0006_auto_20210312_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='journeyuser',
            options={'ordering': ['user__first_name']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['label']},
        ),
    ]
